# Data Preparation Lab -- Module 2, Class 2

**Dataset:** Superstore Sales

In this lab you will:
1. Load and inspect data
2. Handle missing values
3. Remove duplicates
4. Convert data types
5. Create derived features

The first 3 tasks are pre-built. The rest are TODO for you.

---
## Setup: Load the Dataset

Option A: Upload from Kaggle (download from https://www.kaggle.com/datasets/vivek468/superstore-dataset-final)

Option B: Use the URL loader below.

In [9]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vivek468/superstore-dataset-final")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'superstore-dataset-final' dataset.
Path to dataset files: /kaggle/input/superstore-dataset-final

In [10]:
import pandas as pd
import numpy as np

# ---------------------------------------------------------
# SETUP: Loading the Dataset
# ---------------------------------------------------------
# We use a public URL to load the Superstore dataset.
# The 'latin-1' encoding is used to handle special characters correctly.

url = "https://raw.githubusercontent.com/leonism/sample-superstore/master/data/superstore.csv"

try:
    df = pd.read_csv(url, encoding='latin-1')
    print(f"Loaded from URL: {df.shape[0]} rows, {df.shape[1]} columns")
except Exception as e:
    print(f"URL failed ({e}). Use Option A: upload the CSV manually.")
    # If the URL fails, we manually upload the file in Colab.
    from google.colab import files
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]
    df = pd.read_csv(filename, encoding='latin-1')
    print(f"Loaded from upload: {df.shape[0]} rows, {df.shape[1]} columns")

Loaded from URL: 10800 rows, 21 columns

---
## Task 1: Inspect the Data (pre-built)

Always look at your data before doing anything to it.

In [11]:
# ---------------------------------------------------------
# TASK 1: Inspecting the Data
# ---------------------------------------------------------
# View the first 5 rows to understand what the data looks like.
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2017-138688,6/12/2017,6/16/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164

In [12]:
# Print dataset shape (rows, columns)
print(f"Shape: {df.shape[0]} rows, {df.shape[1]} columns")

Shape: 10800 rows, 21 columns

In [ ]:
# Show column data types and non-null counts
# Useful to detect missing values and incorrect types
df.info()

In [ ]:
# Get basic statistics (mean, min, max) for numerical columns.
df.describe()

---
## Task 2: Missing Values (pre-built)

Check which columns have missing values and how many.

In [13]:
# ---------------------------------------------------------
# TASK 2: Handling Missing Values
# ---------------------------------------------------------
# 1. Fill missing numerical values with the median (middle value).
# This is better than the mean because it is not affected by outliers.
# Count missing values in each column
missing = df.isnull().sum()
# Calculate percentage of missing values
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)

# Combine into a report DataFrame
missing_report = pd.DataFrame({
    'missing_count': missing,
    'missing_pct': missing_pct
})

# Show only columns with missing values
missing_report[missing_report['missing_count'] > 0]

               missing_count  missing_pct
Order Date               806         7.46
Ship Date                806         7.46
Ship Mode                806         7.46
Customer ID              806         7.46
Customer Name            806         7.46
Segment                  806         7.46
Country                  806         7.46
City                     806         7.46
State                    806         7.46
Postal Code              817         7.56
Region                   806         7.46
Product ID               806         7.46
Category                 806         7.46
Sub-Category             806         7.46
Product Name             806         7.46
Sales                    806         7.46
Quantity                 806         7.46
Discount                 806         7.46
Profit                   806         7.46

In [14]:
# Select numerical columns (int, float)
numerical_cols = df.select_dtypes(include=[np.number]).columns
# Fill missing numerical values with median
# Median is robust to outliers
for col in numerical_cols:
    if df[col].isnull().sum() > 0:
        median_val = df[col].median()
        df[col].fillna(median_val, inplace=True)
        print(f"Filled {col} missing values with median: {median_val}")

# Select categorical columns (object/string).
categorical_cols = df.select_dtypes(include=['object']).columns
# Fill missing categorical values with mode (most frequent value)
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        mode_val = df[col].mode()[0]
        df[col].fillna(mode_val, inplace=True)
        print(f"Filled {col} missing values with mode: {mode_val}")

# Verify that no missing values remain
print(f"\nTotal missing values remaining: {df.isnull().sum().sum()}")

Filled Postal Code missing values with median: 57103.0
Filled Sales missing values with median: 54.489999999999995
Filled Quantity missing values with median: 3.0
Filled Discount missing values with median: 0.2
Filled Profit missing values with median: 8.6665
Filled Order Date missing values with mode: 9/5/2017
Filled Ship Date missing values with mode: 12/16/2016
Filled Ship Mode missing values with mode: Standard Class
Filled Customer ID missing values with mode: WB-21850
Filled Customer Name missing values with mode: William Brown
Filled Segment missing values with mode: Consumer
Filled Country missing values with mode: United States
Filled City missing values with mode: New York City
Filled State missing values with mode: California
Filled Region missing values with mode: West
Filled Product ID missing values with mode: OFF-PA-10001970
Filled Category missing values with mode: Office Supplies
Filled Sub-Category missing values with mode: Binders
Filled Product Name missing values with mode: Staple envelope

Total missing values remaining: 0

/tmp/ipykernel_1815/3192024586.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)
/tmp/ipykernel_1815/3192024586.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_val, inplace=True)

---
## Task 3: Remove Duplicates (pre-built)

In [15]:
# Count duplicate rows
n_duplicates = df.duplicated().sum()
print(f"Duplicate rows found: {n_duplicates}")

# Remove duplicates if any exist
if n_duplicates > 0:
    df = df.drop_duplicates()
    print(f"After removal: {df.shape[0]} rows remain")
else:
    print("No duplicates to remove.")

Duplicate rows found: 504
After removal: 10296 rows remain

---
## Task 4: Convert Date Columns (TODO)

The `Order Date` and `Ship Date` columns are stored as strings. Convert them to proper datetime objects.

Hint: Use `pd.to_datetime()`. After conversion, verify with `.dtypes`.

In [16]:
# Check current data types of date-related columns
print("Before conversion:")
for col in df.columns:
    if 'date' in col.lower() or 'Date' in col:
        print(f"  {col}: {df[col].dtype}")
        print(f"  Sample value: {df[col].iloc[0]}")

Before conversion:
  Order Date: object
  Sample value: 11/8/2017
  Ship Date: object
  Sample value: 11/11/2017

In [19]:
# Convert date columns from string to datetime format
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

# Verify the conversion by checking the data types.
print("\nDate columns converted. New types:")
print(df[['Order Date', 'Ship Date']].dtypes)

Date columns converted. New types:
Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

---
## Task 5: Derived Features (TODO)

Create customer-level summary features. These are the building blocks for customer segmentation (Activity 4).

You need to create:
- **total_spending**: Total sales per customer
- **order_frequency**: Number of orders per customer
- **avg_order_value**: Average sales amount per order per customer

Hint: Use `df.groupby('Customer ID')` (or whatever the customer ID column is named).

In [ ]:
# First, identify the right column names
print("All columns:")
for col in df.columns:
    print(f"  {col}")

In [27]:
# Display all column names to identify correct fields
for col in df.columns:
    print(col)

# Total spending per customer (sum of Sales)
customer_spending = df.groupby('Customer ID')['Sales'].sum()
customer_spending.name = 'total_spending'

# Order frequency per customer (number of orders)
order_freq = df.groupby('Customer ID').size()
order_freq.name = 'order_frequency'

# Average order value per customer
avg_order = df.groupby('Customer ID')['Sales'].mean()
avg_order.name = 'avg_order_value'

# Combine all features into a single DataFrame
customer_summary = pd.concat(
    [customer_spending, order_freq, avg_order],
    axis=1
)

# Display first 10 rows
customer_summary.head(10)

Row ID
Order ID
Order Date
Ship Date
Ship Mode
Customer ID
Customer Name
Segment
Country
City
State
Postal Code
Region
Product ID
Category
Sub-Category
Product Name
Sales
Quantity
Discount
Profit

             total_spending  order_frequency  avg_order_value
Customer ID
AA-10315           5563.560               11       505.778182
AA-10375           1056.390               15        70.426000
AA-10480           1790.512               12       149.209333
AA-10645           5086.935               18       282.607500
AB-10015            886.156                6       147.692667
AB-10060           7755.620               18       430.867778
AB-10105          14473.571               20       723.678550
AB-10150            966.710               12        80.559167
AB-10165           1113.838               14        79.559857
AB-10255            914.532               14        65.323714

In [28]:
customer_summary.describe()

       total_spending  order_frequency  avg_order_value
count      793.000000       793.000000       793.000000
mean      2917.600051        12.983607       227.742345
std       2717.903575        13.137232       190.416146
min          4.833000         1.000000         2.416500
25%       1146.050000         8.000000       115.485500
50%       2256.394000        12.000000       183.924000
75%       3785.276000        16.000000       282.688947
max      25043.050000       339.000000      1751.292000

---
## Task 6: Save Cleaned Data (TODO)

Save the cleaned DataFrame to a new CSV file. Never overwrite the original.

In [29]:
# Save cleaned dataset
df.to_csv('superstore_cleaned.csv', index=False)

# Save customer summary
customer_summary.to_csv('customer_summary.csv')

print("Files saved successfully!")

Files saved successfully!

In [30]:
from google.colab import files

files.download('superstore_cleaned.csv')
files.download('customer_summary.csv')

# Module 2 | Class 2 Assignment: Python Data Preparation Lab
---
## 📊 Project Overview
This project involves working with the **Superstore Sales Dataset** dataset, cleaning it, and preparing it for analysis (Data Preprocessing).

---

## 📂 Task 1: Import and Load the Data

In [33]:
import pandas as pd


# View the first 10 rows
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164
5,6,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7.0,0.00,14.1694
6,7,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4.0,0.00,1.9656
7,8,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6.0,0.20,90.7152
8,9,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3.0,0.20,5.7825
9,10,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5.0,0.00,34.4700

Using the df.head(10) function, the columns and initial values were checked to ensure the data loaded correctly.

## 🔍 Task 2: Inspect the Structure
> **Process:** Examine the shape, column types, summary statistics, and check for missing values.

In [34]:
# Check table shape and data types
print("Shape:", df.shape)
df.info()
print("\nSummary Statistics:\n", df.describe())
print("\nMissing Values Count:\n", df.isnull().sum())

Shape: (10296, 21)
<class 'pandas.core.frame.DataFrame'>
Index: 10296 entries, 0 to 10798
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10296 non-null  object
 1   Order ID       10296 non-null  object
 2   Order Date     10296 non-null  datetime64[ns]
 3   Ship Date      10296 non-null  datetime64[ns]
 4   Ship Mode      10296 non-null  object
 5   Customer ID    10296 non-null  object
 6   Customer Name  10296 non-null  object
 7   Segment        10296 non-null  object
 8   Country        10296 non-null  object
 9   City           10296 non-null  object
 10  State          10296 non-null  object
 11  Postal Code    10296 non-null  float64
 12  Region         10296 non-null  object
 13  Product ID     10296 non-null  object
 14  Category       10296 non-null  object
 15  Sub-Category   10296 non-null  object
 16  Product Name   10296 non-null  object
 17  Sales          10296 non-null  float64
 18  Quantity       10296 non-null  float64
 19  Discount       10296 non-null  float64
 20  Profit         10296 non-null  float64
dtypes: datetime64[ns](2), float64(5), object(14)
memory usage: 1.7+ MB

Summary Statistics:
                           Order Date                      Ship Date  \
count                          10296                          10296
mean   2017-05-03 23:14:15.944056064  2017-04-30 02:18:44.475524352
min              2015-01-03 00:00:00            2015-01-07 00:00:00
25%              2016-06-06 12:00:00            2016-06-09 18:00:00
50%              2017-07-19 00:00:00            2017-06-09 00:00:00
75%              2018-05-05 00:00:00            2018-05-09 00:00:00
max              2018-12-30 00:00:00            2019-01-05 00:00:00
std                              NaN                            NaN

        Postal Code         Sales      Quantity      Discount        Profit
count  10296.000000  10296.000000  10296.000000  10296.000000  10296.000000
mean   55301.709693    224.714145      3.766414      0.157487     28.070542
min     1040.000000      0.444000      1.000000      0.000000  -6599.978000
25%    23666.000000     17.904000      2.000000      0.000000      1.902400
50%    57103.000000     54.490000      3.000000      0.200000      8.666500
75%    90004.000000    200.998000      5.000000      0.200000     28.172950
max    99301.000000  22638.480000     14.000000      0.800000   8399.976000
std    31549.530875    614.748378      2.196275      0.203536    230.823216

Missing Values Count:
 Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

While analyzing the data structure, the total number of rows and columns was determined. The .info() and .describe() methods were used to examine data types and summary statistics. Additionally, the dataset was checked for any missing (null) values.

## 🛠 Task 3: Handle Missing Values
> **Process:** Clean the data by filling null values using robust statistical methods (median for numbers, mode for categories).

In [35]:
# Fill numerical columns with median and categorical columns with mode
# (Note: If missing values exist, they are handled as follows)
df['Sales'] = df['Sales'].fillna(df['Sales'].median())

# Example for a categorical column:
# df['Ship Mode'] = df['Ship Mode'].fillna(df['Ship Mode'].mode()[0])

print("Missing values after handling:\n", df.isnull().sum())

Missing values after handling:
 Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Statistical methods were applied to fill any gaps in the dataset. The median was chosen for numerical values because it is more robust against outliers. If no missing values were found, the integrity of the data was confirmed.

## 🧹 Task 4: Remove Duplicates
> **Process:** Identify identical rows and remove them to ensure data unique integrity.

In [36]:
# Check for and remove duplicate rows
print("Number of duplicate rows:", df.duplicated().sum())
df = df.drop_duplicates()
print("Shape after removing duplicates:", df.shape)

Number of duplicate rows: 0
Shape after removing duplicates: (10296, 21)

To prevent errors in the analysis, duplicate rows in the table were identified and removed using drop_duplicates(). This process improves the accuracy and quality of the data.

## 📅 Task 5: Convert Data Types
> **Process:** Transform date columns into proper `datetime` objects to enable time-based analysis.

In [38]:
# Convert date columns to the correct format
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

print(df[['Order Date', 'Ship Date']].dtypes)
df[['Order Date', 'Ship Date']].head()

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

  Order Date  Ship Date
0 2017-11-08 2017-11-11
1 2017-11-08 2017-11-11
2 2017-06-12 2017-06-16
3 2016-10-11 2016-10-18
4 2016-10-11 2016-10-18

The Order Date and Ship Date columns were converted from string format to datetime format. This allows for time-based analysis (by year, month, or week) and the calculation of time intervals in future steps.

## 📈 Task 6: Create Derived Features
> **Process:** Group data by Customer ID to calculate total spending, order frequency, and average order value, then export the final CSV files.

In [39]:
# Calculate customer-level summary metrics
total_spending = df.groupby('Customer ID')['Sales'].sum().reset_index()
total_spending.columns = ['Customer ID', 'total_spending']

order_freq = df.groupby('Customer ID')['Order ID'].nunique().reset_index()
order_freq.columns = ['Customer ID', 'order_frequency']

avg_order = df.groupby('Customer ID')['Sales'].mean().reset_index()
avg_order.columns = ['Customer ID', 'avg_order_value']

# Merge the tables
customer_summary = total_spending.merge(order_freq, on='Customer ID').merge(avg_order, on='Customer ID')

# Save the cleaned data
df.to_csv('superstore_cleaned.csv', index=False)
customer_summary.to_csv('customer_summary.csv', index=False)

customer_summary.head(10)

  Customer ID  total_spending  order_frequency  avg_order_value
0    AA-10315        5563.560                5       505.778182
1    AA-10375        1056.390                9        70.426000
2    AA-10480        1790.512                4       149.209333
3    AA-10645        5086.935                6       282.607500
4    AB-10015         886.156                3       147.692667
5    AB-10060        7755.620                8       430.867778
6    AB-10105       14473.571               10       723.678550
7    AB-10150         966.710                5        80.559167
8    AB-10165        1113.838                8        79.559857
9    AB-10255         914.532                9        65.323714

In the final stage, a summary table was created for each customer, calculating total spending, order frequency, and average order value. The cleaned and processed data were then saved into new CSV files for further analysis